# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
os:
- linux
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended
  texlive-fonts-extra
- tlmgr install standalone
addons:
  apt:
    update:
    - true
    sources:
    - sourceline: ppa:opencpu/imagemagick
    packages:
    - libmagick++-dev
r_packages:
- devtools
- pkgdown
r_github_packages:
- metrumresearchgroup/covrpage
after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  github-token: "$GITHUB_PAT"
  keep-history: true
  local-dir: docs
  on:
    branch: master